package headers

const CONTENT_TYPE = "Content-Type"
const AUTHORIZATION = "Authorization"
const X_TOTAL_COUNT = "X-Total-Count"
const CONTENT_DISPOSITION = "Content-Disposition"
const X_SERVICE_NAME = "X-Service-Name"
const X_SERVICE_VERSION = "X-Service-Version"
const X_POWERED_BY = "X-Powered-By"
const X_CONTENT_TYPE_OPTIONS = "X-Content-Type-Options"
const X_XSS_PROTECTION = "X-XSS-Protection"
const X_FRAME_OPTIONS = "X-Frame-Options"
const X_REQUEST_ID = "X-Request-Id"
const STRICT_TRANSPORT_SECURITY = "Strict-Transport-Security"
const CONTENT_SECURITY_POLICY = "Content-Security-Policy"
const ACCESS_CONTROL_ALLOW_ORIGIN = "Access-Control-Allow-Origin"
const ACCESS_CONTROL_EXPOSE_HEADERS = "Access-Control-Expose-Headers"
const ACCESS_CONTROL_ALLOW_CREDENTIALS = "Access-Control-Allow-Credentials"
const ACCESS_CONTROL_ALLOW_METHODS = "Access-Control-Allow-Methods"
const ACCESS_CONTROL_ALLOW_HEADERS = "Access-Control-Allow-Headers"
const TIMING_ALLOW_ORIGIN = "Timing-Allow-Origin"
